# UTNixOS_Pro 模块选择逻辑（script/lib/selection.sh）
# 根据菜单选择修改 configuration.nix / home-manager.nix 的 imports，
# 并把选择保存到 .utnixos-pro-selection 以便下次恢复。

# 依赖：env.sh（STATE_FILE 等）、util.sh（info/ok/sed 辅助）

# ---------- 根据选择修改配置文件 ----------
apply_selection() {
  local CFG="$TARGET_DIR/configuration.nix"
  [[ -f "$CFG" ]] || die nofile_cfg "$CFG"
  info apply_write "$CFG"

  # 兜底默认值（非交互路径：如用环境变量预设 DESKTOP 直接安装时）
  DESKTOP="${DESKTOP:-xfce}"
  BOOT="${BOOT:-grub-uefi}"
  GRUB_THEME="${GRUB_THEME:-no}"
  GRUB_DEVICE="${GRUB_DEVICE:-}"
  LOCALE="${LOCALE:-en_US}"
  INPUT="${INPUT:-ibus}"
  MIRROR="${MIRROR:-ustc}"
  USERSHELL="${USERSHELL:-zsh}"
  SYSTEM_MODULES="${SYSTEM_MODULES:-auto-update clean nix-command zram fonts webui}"
  ADVANCED="${ADVANCED:-}"

  # 桌面环境（单选）
  comment_import "$CFG" "desktop/"
  uncomment_import "$CFG" "desktop/${DESKTOP}.nix"

  # 引导（单选：grub-uefi / grub-bios / systemd-boot；GRUB 时按 GRUB_THEME 决定主题）
  comment_import "$CFG" "boot/"
  case "$BOOT" in
    systemd-boot) uncomment_import "$CFG" "boot/systemd-boot.nix" ;;
    grub-bios)    uncomment_import "$CFG" "boot/grub-bios.nix" ;;
    *)            uncomment_import "$CFG" "boot/grub.nix" ;;
  esac
  if [[ "${GRUB_THEME:-no}" == "yes" ]]; then
    uncomment_import "$CFG" "boot/grub-theme.nix"
  fi
  write_grub_device

  # 语言环境（单选）
  comment_import "$CFG" "locale/"
  uncomment_import "$CFG" "locale/${LOCALE}.nix"

  # 输入法（单选）
  comment_import "$CFG" "input/"
  uncomment_import "$CFG" "input/${INPUT}.nix"

  # 镜像源（单选）
  comment_import "$CFG" "mirrors/"
  uncomment_import "$CFG" "mirrors/${MIRROR}.nix"

  # 默认 Shell（单选：zsh / bash / fish）
  comment_import "$CFG" "shell/"
  uncomment_import "$CFG" "shell/${USERSHELL}.nix"

  # 同步修改 home-manager 里的 shell 配置导入
  local HM="$TARGET_DIR/home/home-manager.nix"
  if [[ -f "$HM" ]]; then
    sed -i -E "s|^([[:space:]]*)#?(\./shell/[^#]*)|\1#\2|" "$HM"
    sed -i -E "s|^([[:space:]]*)#(\./shell/${USERSHELL}\.nix[^#]*)|\1\2|" "$HM"
  fi

  # 系统模块（多选）
  local m
  for m in auto-update clean nix-command zram fonts nopwdtodesktop vm-debug webui; do
    if [[ " $SYSTEM_MODULES " == *" $m "* ]]; then
      uncomment_import "$CFG" "system/${m}.nix"
    else
      comment_import "$CFG" "system/${m}.nix"
    fi
  done

  # 进阶模块（多选）
  for m in secrets impermanence backup security; do
    if [[ " $ADVANCED " == *" $m "* ]]; then
      uncomment_import "$CFG" "system/${m}.nix"
    else
      comment_import "$CFG" "system/${m}.nix"
    fi
  done

  # 保存选择状态
  save_state
  ok apply_done
}

# ---------- GRUB(BIOS) 目标磁盘（机器本地文件 host/grub-device.nix） ----------
# configuration.nix 始终 import 该文件；非 grub-bios 时内容为空模块，不产生配置。
write_grub_device() {
  local f="$TARGET_DIR/host/grub-device.nix"
  mkdir -p "$TARGET_DIR/host"
  if [[ "$BOOT" == "grub-bios" && -n "${GRUB_DEVICE:-}" ]]; then
    cat > "$f" <<EOF
# UTNixOS_Pro - GRUB(BIOS) 引导设备（机器本地文件，自动维护）
# 警告：此文件由安装脚本 / Web 管理面板自动写入，请勿手动编辑；ut update 时会自动保留。
{ ... }: {
  boot.loader.grub.device = "${GRUB_DEVICE}";
}
EOF
  else
    cat > "$f" <<'EOF'
# UTNixOS_Pro - GRUB(BIOS) 引导设备（机器本地文件，自动维护）
# 当前为空模块：表示未使用 GRUB(BIOS)，不产生任何配置。
{ ... }: { }
EOF
  fi
}

# ---------- 选择状态持久化 ----------
save_state() {
  local st="$TARGET_DIR/$STATE_FILE"
  cat > "$st" <<EOF
# UTNixOS_Pro module selection state (generated by install.sh; edit then re-run update)
DESKTOP=$DESKTOP
BOOT=$BOOT
GRUB_THEME=${GRUB_THEME:-no}
GRUB_DEVICE=${GRUB_DEVICE:-}
LOCALE=$LOCALE
INPUT=$INPUT
MIRROR=$MIRROR
USERSHELL=$USERSHELL
SYSTEM_MODULES=$SYSTEM_MODULES
ADVANCED=$ADVANCED
EOF
}

load_state() {
  local st="$TARGET_DIR/$STATE_FILE"
  if [[ -f "$st" ]]; then
    # 逐行解析，不能用 . (source)！
    # 原因：SYSTEM_MODULES=auto-update clean nix-command ... 这类多值行被 source 时，
    # shell 会把「clean nix-command ...」当成命令执行（clean: command not found + set -e 直接退出）。
    # 这里与 Web 面板（webui/internal/config/selection.go 的 LoadState）保持同一套解析语义。
    local k v line
    while IFS= read -r line; do
      [[ "$line" == \#* || -z "$line" ]] && continue
      k="${line%%=*}"
      v="${line#*=}"
      case "$k" in
        DESKTOP)       DESKTOP="$v" ;;
        BOOT)          BOOT="$v" ;;
        GRUB_THEME)    GRUB_THEME="$v" ;;
        GRUB_DEVICE)   GRUB_DEVICE="$v" ;;
        LOCALE)        LOCALE="$v" ;;
        INPUT)         INPUT="$v" ;;
        MIRROR)        MIRROR="$v" ;;
        USERSHELL)     USERSHELL="$v" ;;
        SYSTEM_MODULES) SYSTEM_MODULES="$v" ;;
        ADVANCED)      ADVANCED="$v" ;;
      esac
    done < "$st"
    # 旧版本状态兼容：grub-theme/grub-notheme → grub-uefi + 主题开关
    case "${BOOT:-}" in
      grub-theme)   BOOT="grub-uefi"; GRUB_THEME=yes ;;
      grub-notheme) BOOT="grub-uefi"; GRUB_THEME=no ;;
    esac
    GRUB_THEME="${GRUB_THEME:-no}"
    GRUB_DEVICE="${GRUB_DEVICE:-}"
    ok state_restored
  fi
}

# ---------- 交互式选择全部模块 ----------
# GRUB(BIOS) 目标磁盘：列出检测到的磁盘 + 手动输入（回车默认 /dev/sda）
pick_grub_device() {
  local detected=""
  if command -v lsblk >/dev/null 2>&1; then
    detected="$(lsblk -dno NAME,SIZE,MODEL -e 7,11 2>/dev/null || true)"
  fi
  if [[ -n "$detected" ]]; then
    info t_grub_disk_list
    local d
    while IFS= read -r d; do
      [[ -n "$d" ]] && say "    /dev/$d"
    done <<< "$detected"
  fi
  prompt t_grub_disk_manual
  read -r GRUB_DEVICE < /dev/tty || GRUB_DEVICE="/dev/sda"
  GRUB_DEVICE="$(printf '%s' "$GRUB_DEVICE" | tr -d '[:space:]')"
  [[ -n "$GRUB_DEVICE" ]] || GRUB_DEVICE="/dev/sda"
  if [[ "$GRUB_DEVICE" != /dev/* ]]; then
    warn t_grub_disk_invalid "$GRUB_DEVICE"
    GRUB_DEVICE="/dev/sda"
  fi
  if [[ -e "$GRUB_DEVICE" ]]; then
    ok t_grub_disk_set "$GRUB_DEVICE"
  else
    warn t_grub_disk_missing "$GRUB_DEVICE"
  fi
}

run_menu() {
  say ""
  say "${C_BOLD}$(_t menu_intro)${C_RESET}"
  say "${C_YELLOW}$(_t menu_hint)${C_RESET}"

  # 先选引导加载器：GRUB(UEFI) / GRUB(BIOS) / systemd-boot
  pick_one t_boot grub-uefi grub-bios systemd-boot
  BOOT="$PICKED"

  # 选了 GRUB 再问要不要主题；GRUB(BIOS) 还要确认目标磁盘（MBR 引导需要）
  GRUB_THEME="no"
  GRUB_DEVICE=""
  if [[ "$BOOT" == grub-* ]]; then
    prompt t_grub_theme_q
    local ans=""
    read -r ans < /dev/tty || ans="y"
    [[ "$ans" =~ ^[Nn]$ ]] || GRUB_THEME="yes"
    if [[ "$BOOT" == grub-bios ]]; then
      pick_grub_device
    fi
  fi

  pick_one t_desktop xfce gnome kde lxqt hyprland cosmic
  DESKTOP="$PICKED"

  pick_one t_locale en_US zh_CN
  LOCALE="$PICKED"

  pick_one t_input ibus fcitx5
  INPUT="$PICKED"

  pick_one t_mirror ustc tuna nju sjtu
  MIRROR="$PICKED"

  pick_one t_shell zsh bash fish
  USERSHELL="$PICKED"

  pick_multi t_sysmods "auto-update clean nix-command zram fonts webui" \
    auto-update clean nix-command zram fonts webui nopwdtodesktop vm-debug
  SYSTEM_MODULES="$PICKED_MULTI"

  pick_multi t_advmods "" secrets impermanence backup security
  ADVANCED="$PICKED_MULTI"
}

# ---------- 展示当前选择 ----------
show_selection() {
  say ""
  say "${C_BOLD}$(_t cur_selection)${C_RESET}"
  say "  $(_t lab_desktop) : $(opt_label "${DESKTOP:-xfce}")"
  say "  $(_t lab_boot) : $(opt_label "${BOOT:-grub-uefi}")"
  if [[ "${BOOT:-grub-uefi}" == grub-* ]]; then
    say "    $(_t lab_grub_theme) : ${GRUB_THEME:-no}"
  fi
  if [[ "${BOOT:-grub-uefi}" == grub-bios ]]; then
    say "    $(_t lab_grub_device) : ${GRUB_DEVICE:-/dev/sda}"
  fi
  say "  $(_t lab_locale) : $(opt_label "${LOCALE:-en_US}")"
  say "  $(_t lab_input) : $(opt_label "${INPUT:-ibus}")"
  say "  $(_t lab_mirror) : $(opt_label "${MIRROR:-ustc}")"
  say "  $(_t lab_shell) : $(opt_label "${USERSHELL:-zsh}")"
  say "  $(_t lab_sysmods) : $(label_list "${SYSTEM_MODULES:-auto-update clean nix-command zram fonts webui}")"
  if [[ -n "${ADVANCED:-}" ]]; then
    say "  $(_t lab_advmods) : $(label_list "$ADVANCED")"
  else
    say "  $(_t lab_advmods) : $(_t val_none)"
  fi
  say ""
}
